const clickBtoMC = () => {setCount(count + a); setTeam([...team, {name: mcName, time: 0.25, count: count }]);}
const clickBtoLE = () => {setCount(count + a); setTeam([...team, {name: leName, time: 0.25, count: count }]);}
const clickBtoMV = () => {setCount(count + a); setTeam([...team, {name: mvName, time: 0.25, count: count }]);}
const clickBtoHQ = () => {setCount(count + a); setTeam([...team, {name: hqName, time: 0.25, count: count }]);}
const clickBtoSL = () => {setCount(count + a); setTeam([...team, {name: slName, time: 0.25, count: count }]);}
const clickBtoSG = () => {setCount(count + a); setTeam([...team, {name: sgName, time: 0.25, count: count }]);}
const clickBtoCG = () => {setCount(count + a); setTeam([...team, {name: cgName, time: 0.25, count: count }]);}
const clickBtoPG = () => {setCount(count + a); setTeam([...team, {name: pgName, time: 0.25, count: count }]);}
const clickBtoED = () => {setCount(count + a); setTeam([...team, {name: edName, time: 0.25, count: count }]);}
const clickBtoEH = () => {setCount(count + a); setTeam([...team, {name: ehName, time: 0.25, count: count }]);}
const clickBtoJG = () => {setCount(count + a); setTeam([...team, {name: jgName, time: 0.25, count: count }]);}
const clickBtoWQ = () => {setCount(count + a); setTeam([...team, {name: wqName, time: 0.25, count: count }]);}
const clickBtoWP = () => {setCount(count + a); setTeam([...team, {name: wpName, time: 0.25, count: count }]);}
const clickBtoMT = () => {setCount(count + a); setTeam([...team, {name: mtName, time: 0.25, count: count }]);}
const clickBtoCH = () => {setCount(count + a); setTeam([...team, {name: chName, time: 0.25, count: count }]);}
const clickBtoFL = () => {setCount(count + a); setTeam([...team, {name: flName, time: 0.25, count: count }]);}
const clickBtoEN = () => {setCount(count + a); setTeam([...team, {name: enName, time: 0.25, count: count }]);}